// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreateExperienceController from "./create_experience_controller"
application.register("create-experience", CreateExperienceController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
